# --------------------------     Fonts     ------------------------
font:
  normal:
    family: FiraCode Nerd Font
    style: Regular

  bold:
    family: FiraCode Nerd Font
    style: Bold

  italic:
    family: FiraCode Nerd Font
    style: Italic

  bold_italic:
    family: FiraCode Nerd Font
    style: Bold Italic

  size: 11

# -------------------------- Color Schemes ------------------------
schemes:
  nord_monokai: &nord_monokai
    primary:
      background: '#2E3440'
      foreground: '#D8DEE9'

    # Normal colors
    normal:
      black:   '#403E41'
      red:     '#FF6188'
      green:   '#A9DC76'
      yellow:  '#FFD866'
      blue:    '#FC9867'
      magenta: '#AB9DF2'
      cyan:    '#78DCE8'
      # white:   '#FCFCFA'
      white:   '#FFFFFF'

    # Bright colors
    bright:
      black:   '#727072'
      red:     '#FF6188'
      green:   '#A9DC76'
      yellow:  '#FFD866'
      blue:    '#FC9867'
      magenta: '#AB9DF2'
      cyan:    '#78DCE8'
      # white:   '#FCFCFA'
      white:   '#FFFFFF'

  nord: &nord
    # Default colors
    primary:
      background: '#2E3440'
      foreground: '#D8DEE9'

    # Normal colors
    normal:
      black:   '#3B4252'
      red:     '#BF616A'
      green:   '#A3BE8C'
      yellow:  '#EBCB8B'
      blue:    '#81A1C1'
      magenta: '#B48EAD'
      cyan:    '#88C0D0'
      white:   '#E5E9F0'

    # Bright colors
    bright:
      black:   '#4C566A'
      red:     '#BF616A'
      green:   '#A3BE8C'
      yellow:  '#EBCB8B'
      blue:    '#81A1C1'
      magenta: '#B48EAD'
      cyan:    '#8FBCBB'
      white:   '#ECEFF4'

  monokai_pro: &monokai_pro
    primary:
      background: '#2D2A2E'
      foreground: '#FCFCFA'

    # Normal colors
    normal:
      black:   '#403E41'
      red:     '#FF6188'
      green:   '#A9DC76'
      yellow:  '#FFD866'
      blue:    '#FC9867'
      magenta: '#AB9DF2'
      cyan:    '#78DCE8'
      white:   '#FCFCFA'

    # Bright colors
    bright:
      black:   '#727072'
      red:     '#FF6188'
      green:   '#A9DC76'
      yellow:  '#FFD866'
      blue:    '#FC9867'
      magenta: '#AB9DF2'
      cyan:    '#78DCE8'
      white:   '#FCFCFA'
      
  monokai: &monokai
    primary:
      background: '#272822'
      foreground: '#F8F8F2'

    # Normal colors
    normal:
      black:   '#272822'
      red:     '#F92672'
      green:   '#A6E22E'
      yellow:  '#F4BF75'
      blue:    '#66D9EF'
      magenta: '#AE81FF'
      cyan:    '#A1EFE4'
      white:   '#F8F8F2'

    # Bright colors
    bright:
      black:   '#75715E'
      red:     '#F92672'
      green:   '#A6E22E'
      yellow:  '#F4BF75'
      blue:    '#66D9EF'
      magenta: '#AE81FF'
      cyan:    '#A1EFE4'
      white:   '#F9F8F5'

  ayu_dark: &ayu_dark
    primary:
      background: '#0A0E14'
      foreground: '#B3B1AD'

    # Normal colors
    normal:
      black: '#01060E'
      red: '#EA6C73'
      green: '#91B362'
      yellow: '#F9AF4F'
      blue: '#53BDFA'
      magenta: '#FAE994'
      cyan: '#90E1C6'
      white: '#C7C7C7'

    # Bright colors
    bright:
      black: '#686868'
      red: '#F07178'
      green: '#C2D94C'
      yellow: '#FFB454'
      blue: '#59C2FF'
      magenta: '#FFEE99'
      cyan: '#95E6CB'
      white: '#FFFFFF'

  molokai_dark: &molokai_dark
    # Default colors
    primary:
      background: '#1B1D1E'
      foreground: '#F8F8F2'
    # Normal colors
    normal:
      black:   '#333333'
      red:     '#C4265E'
      green:   '#86B42B'
      yellow:  '#B3B42B'
      blue:    '#6A7EC8'
      magenta: '#8C6BC8'
      cyan:    '#56ADBC'
      white:   '#E3E3DD'
    # Bright colors
    bright:
      black:   '#666666'
      red:     '#F92672'
      green:   '#A6E22E'
      yellow:  '#E2E22E'
      blue:    '#819AFF'
      magenta: '#AE81FF'
      cyan:    '#66D9EF'
      white:   '#F8F8F2'


colors: *nord_monokai